# Docker compose file that builds images and runs the containers needed for
# development. You need to have your MJKEY set in the environment.
#
# docker-compose \
#     -f ./docker/docker-compose.dev.yml \
#     build \
#         --build-arg MJKEY="$(cat ~/.mujoco/mjkey.txt)"

version: "2.4"
services:
  mslac-dev-gpu:
    image: ${IMAGE_NAME:-mslac}:${IMAGE_TAG:-latest}-gpu
    container_name: mslac-dev-gpu
    runtime: nvidia
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - ${IMAGE_NAME:-mslac}:latest-gpu
      args:
        - MJKEY
    init: true
    working_dir: /root/mslac
    ports:
      - "6006"  # Tensorboard
      - "5000"  # Viskit
      - "8888"  # Jupyter
    volumes:
       - ~/.mujoco/mjkey.txt:/root/.mujoco/mjkey.txt
       - ..:/root/mslac
    command:
      - bash
    stdin_open: true
    tty: true
